### ISSUE TITLE
What constitutes "Failed to receive challenge"?

### ISSUE THREAD

**Issue by Codewow** [Lukasss93/PHP-Minecraft-Server-Status#1]
What exactly constitutes the "Failed to receive challenge" error?

Is it that no data was returned at all, did the server block the request? I'm still relatively new to Web Development and I can't figure out what's causing the attempt to query MCPE to fail on my live server and not my internal server.

Sorry to bug you.

**Comment by Lukasss93** [comment]
1) Are you sure G4S (query) server is running?
The server console should show up in logs like this:
```
[INFO] Starting G4S status listener
[INFO] Query running on 0.0.0.0:25565
```
Look server.properties for that:
```
enable-query=true
query.port=25565
```
2) Are you quering on the right port?
3) Try checking your php error log, it could be having some errors.
4) Maybe that port is blocked by firewall or something else like that? You need to open the UDP port you are quering at your webhost.

**Comment by Codewow** [comment]
It has to be #4, which is weird because querying Java Edition servers works just fine. It only doesn't work for Bedrock servers. I'm specificly testing on the latest version of pocketmine.

**Comment by Lukasss93** [comment]
Very weird... I've tested it right now with a random pocket-mine server:
![phpstorm64_2018-10-09_00-26-59](https://user-images.githubusercontent.com/4071613/46637282-bc838b00-cb5b-11e8-81c8-323581f0cb1b.png)

**Comment by Codewow** [comment]
Yeah. It has to be the host blocking something specific to it. My internal server can query just fine. The unfortunate part is that there are absolutely no errors coming from PHP to give me any clues. All I get is "failed to receive challenge" which doesn't help me much in my situation. Are there any other ways to debug the socket connection?

**Comment by lifewcody** [comment]
@Codewow would it be possible for you to do a wireshark capture on your PC and on your server as well?

**Comment by Codewow** [comment]
Unfortunately I don’t have that kind of access to the server I use. 

I’ll figure it out at some point. Thanks for the suggestions.
