### ISSUE TITLE
Loading Notification?

### ISSUE THREAD

**Issue by cj3636** [Lukasss93/PHP-Minecraft-Server-Status#4]
Is there some way to denote that the PHP script is attempting connection?

I have a issue where while the ping is contacting the server, the surrounding PHP/HTML fails to load in.

I am not a skilled PHP developer so I apologize if there is an obvious answer.

**Comment by Lukasss93** [comment]
Can you send me the contacted server ip or/and your example code?

**Comment by cj3636** [comment]
This is all loaded in to the main page via PHP require();
Basically if the server is _down_, all of the code below waits to load in until the Ping has timed out.
I would like the surrounding HTML to somehow load in before your PHP ping is returned.
I have tried placing the PHP in another file, but it still waits to load all of the code until the ping times out.

```
<!--Vanilla Card-->
<div class="card">
    <div class="content">
        <img alt="TYS ATMR+ LOGO" class="right floated small ui image" src="img/TYS_VANILLA.png">
        <div class="header">
            Vanilla
        </div>
        <div class="meta">
            Vanilla Minecraft with Plugins
        </div>
        <div class="description">
            An experience you can't miss, with an Earth map and more.
        </div>
        <div class="ui divider"></div>
        <div class="extra content">
            <button id="copyVanilla" data-clipboard-text="theyellowsub.us" data-tooltip="Copy Vanilla IP Address"
                    data-inverted="" class="ui huge green button"><i class="copy outline left icon"></i>Vanilla IP
            </button>
        </div>
        <div class="extra content">
            <?php
            require_once('vendor/autoload.php');
            $response = MCPing::check('theyellowsub.us');
            echo $response->getMotdToHtml();
            if ($response->online) {
                echo '<div class="ui green paragraph">Server is UP</div>';
                echo '<div class="ui blue paragraph">' . $response->players . ' Online</div>';
            } else {
                echo '<div class="ui red paragraph">Server is DOWN</div>';
            }
            ?>
        </div>
    </div>
</div>
```

**Comment by Lukasss93** [comment]
This is how PHP works...
PHP is a server side language. You can't load html before your php script ends...
To accomplish your goal, you need to call your separate php script via AJAX with javascript.

**Comment by cj3636** [comment]
> This is how PHP works...
> PHP is a server side language. You can't load html before your php script ends...
> To accomplish your goal, you need to call your separate php script via AJAX with javascript.

Okay, thank you I apologize for openening a ticket for this then.
