### ISSUE TITLE
Cannot get information from server which have use port 19132

### ISSUE THREAD

**Issue by sinhpn92** [Lukasss93/PHP-Minecraft-Server-Status#5]
Hi team,
I did try to use this lib to fetch server infor of `bw.lbsg.net:19132`. But I have got error this server not online.
What's wrong here?

**Comment by Lukasss93** [comment]
Hi! 
MCPing may not work on some servers...

Try MCQuery:

![firefox_5oIrT7DPm8](https://user-images.githubusercontent.com/4071613/98859192-10ab7880-2462-11eb-8bae-055fc17d1374.png)
