### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Surax23** [Lukasss93/PHP-Minecraft-Server-Status#6]
Good day! Sorry for english in advance.
I have Ubuntu server 20.04 LTS with php 7.4.3 with already installed json and iconv.
Trying to manually connect your library to my site like in the example:
`	error_reporting(E_ALL);
	require_once('MCPing/MCPing.php');
	use MCServerStatus\MCPing;
	$response=MCPing::check('flamegarth.ru');
	var_dump($response);
	var_dump($response->toArray());`
And I'm getting HTTP 500 without any errors.
If I comment string with "$response" and other lines in the bottom than nothing happens. Have tried to wrap it in try-catch but no results.
What have I done?

**Comment by Lukasss93** [comment]
You must install this library via composer to make it works

Example:
![image](https://user-images.githubusercontent.com/4071613/159004629-3260c78a-eef5-488e-b75e-f4bc6e396872.png)

**Comment by Surax23** [comment]
Is there any way to use your library wothout installing Composer?

**Comment by Lukasss93** [comment]
No

**Comment by Surax23** [comment]
Ok. After installing it by composer error 500 still exists. I think this shouldn't be your class, but some config misconfiguration. Will try to figure it out. Thank you.
